#!/usr/bin/env bash

PROJECT_DIR=$PWD

# 安装扩展
composer install

# 数据库地址
HOSTNAME=$(cat .env | grep -E '^DB_HOST=' | awk -F"=" '{print $2}')
# 数据库端口
PORT=$(cat .env | grep -E '^DB_PORT=' | awk -F"=" '{print $2}')
# 数据库用户名
USERNAME=$(cat .env | grep -E '^DB_USERNAME=' | awk -F"=" '{print $2}')
# 数据库密码
PASSWORD=$(cat .env | grep -E '^DB_PASSWORD=' | awk -F"=" '{print $2}')
# 数据库名称
DBNAME=$(cat .env | grep -E '^DB_DATABASE=' | awk -F"=" '{print $2}')

# 创建数据库
create_db_sql="create database IF NOT EXISTS ${DBNAME}"
mysql -h${HOSTNAME} -P${PORT} -u${USERNAME} -p${PASSWORD} -e "${create_db_sql}"

# 重新加载类的映射关系
composer dump-autoload

# 创建数据库并填充数据
php artisan migrate:refresh --seed

# 清空所有缓存
php artisan cache:clear
php artisan config:clear
php artisan event:clear
php artisan optimize:clear
php artisan route:clear
php artisan view:clear

# 建立项目文件存储软连接
php artisan storage:link
